apiVersion: v1
data:
  authd.pass: cGFzc3dvcmQ=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"authd.pass":"cGFzc3dvcmQ="},"kind":"Secret","metadata":{"annotations":{},"name":"wazuh-authd-pass","namespace":"security"}}
  creationTimestamp: "2026-05-02T04:43:05Z"
  name: wazuh-authd-pass
  namespace: security
  resourceVersion: "53482"
  uid: 2ab02296-3339-4de9-8975-8bfa6364cfd5
type: Opaque
