apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: iiot-poc
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
