apiVersion: v1
data:
  schema.json: |
    {
      "timestamp_utc": "ISO-8601 UTC timestamp",
      "scenario": "SCENARIO_C",
      "source_namespace": "iiot-poc",
      "component": "health-app|telemetry-api|vulnerable-app|mosquitto|iiot-sensor",
      "event_type": "baseline_security_probe|iiot_security_event",
      "iiot_lab": {
        "scenario": "SCENARIO_C",
        "attack_id": "NONE|T0809|T0814|T0860",
        "asset": "IIoT component name",
        "zone": "iiot-poc",
        "iteration": "integer"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"schema.json":"{\n  \"timestamp_utc\": \"ISO-8601 UTC timestamp\",\n  \"scenario\": \"SCENARIO_C\",\n  \"source_namespace\": \"iiot-poc\",\n  \"component\": \"health-app|telemetry-api|vulnerable-app|mosquitto|iiot-sensor\",\n  \"event_type\": \"baseline_security_probe|iiot_security_event\",\n  \"iiot_lab\": {\n    \"scenario\": \"SCENARIO_C\",\n    \"attack_id\": \"NONE|T0809|T0814|T0860\",\n    \"asset\": \"IIoT component name\",\n    \"zone\": \"iiot-poc\",\n    \"iteration\": \"integer\"\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"security-event-schema","app.kubernetes.io/part-of":"iiot-correlation-lab","iiot-lab/scenario":"C"},"name":"scenario-c-security-event-schema","namespace":"security"}}
  creationTimestamp: "2026-05-02T04:43:01Z"
  labels:
    app.kubernetes.io/component: security-event-schema
    app.kubernetes.io/part-of: iiot-correlation-lab
    iiot-lab/scenario: C
  name: scenario-c-security-event-schema
  namespace: security
  resourceVersion: "53441"
  uid: bba7e4e0-e986-4661-818c-753e8f86fe4d
