apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"default-addresspool","namespace":"metallb-system"},"spec":{"addresses":["10.10.0.150-10.10.0.199"]}}
    creationTimestamp: "2026-05-01T22:32:37Z"
    generation: 1
    name: default-addresspool
    namespace: metallb-system
    resourceVersion: "808"
    uid: b950525d-8424-488c-952e-42ced88570fa
  spec:
    addresses:
    - 10.10.0.150-10.10.0.199
    autoAssign: true
kind: List
metadata:
  resourceVersion: ""
