apiVersion: v1
kind: Service
metadata:
  name: wazuh-dashboard-lb
  namespace: security
  labels:
    app.kubernetes.io/part-of: iiot-correlation-lab
    app.kubernetes.io/component: wazuh-dashboard
    iiot-lab/scenario: C
  annotations:
    metallb.io/loadBalancerIPs: "10.10.0.161"
    metallb.universe.tf/loadBalancerIPs: "10.10.0.161"
spec:
  type: LoadBalancer
  selector:
    app: wazuh-dashboard
  ports:
    - name: https-dashboard
      port: 443
      targetPort: 5601
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager-lb
  namespace: security
  labels:
    app.kubernetes.io/part-of: iiot-correlation-lab
    app.kubernetes.io/component: wazuh-manager
    iiot-lab/scenario: C
  annotations:
    metallb.io/loadBalancerIPs: "10.10.0.162"
    metallb.universe.tf/loadBalancerIPs: "10.10.0.162"
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: agent-events
      port: 1514
      targetPort: 1514
      protocol: TCP
    - name: agent-registration
      port: 1515
      targetPort: 1515
      protocol: TCP
    - name: wazuh-api
      port: 55000
      targetPort: 55000
      protocol: TCP
