apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"default-advertise-all-pools","namespace":"metallb-system"}}
    creationTimestamp: "2026-05-01T22:32:37Z"
    generation: 1
    name: default-advertise-all-pools
    namespace: metallb-system
    resourceVersion: "809"
    uid: 65d15914-9217-432c-a59f-9e42c3796055
kind: List
metadata:
  resourceVersion: ""
