apiVersion: v1
data:
  password: TXlTM2NyMzdQNDUwci4qLQ==
  username: d2F6dWgtd3Vp
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"TXlTM2NyMzdQNDUwci4qLQ==","username":"d2F6dWgtd3Vp"},"kind":"Secret","metadata":{"annotations":{},"name":"wazuh-api-cred","namespace":"security"}}
  creationTimestamp: "2026-05-02T04:43:05Z"
  name: wazuh-api-cred
  namespace: security
  resourceVersion: "53481"
  uid: 1f7be7f0-827c-4b24-85cd-9688ca1e4e91
type: Opaque
