apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wazuh-indexer"},"name":"indexer","namespace":"security"},"spec":{"ports":[{"name":"indexer-rest","port":9200,"targetPort":9200}],"selector":{"app":"wazuh-indexer"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-05-02T04:43:06Z"
  labels:
    app: wazuh-indexer
  name: indexer
  namespace: security
  resourceVersion: "53676"
  uid: c5692fe5-b795-4623-a298-91b18534d31d
spec:
  clusterIP: 10.152.183.51
  clusterIPs:
  - 10.152.183.51
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: indexer-rest
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: wazuh-indexer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
