apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wazuh-manager"},"name":"wazuh-cluster","namespace":"security"},"spec":{"clusterIP":"None","ports":[{"name":"cluster","port":1516,"targetPort":1516}],"selector":{"app":"wazuh-manager"}}}
  creationTimestamp: "2026-05-02T04:43:07Z"
  labels:
    app: wazuh-manager
  name: wazuh-cluster
  namespace: security
  resourceVersion: "53511"
  uid: 8c3adaaf-8b20-4519-931b-e930a34243fd
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: cluster
    port: 1516
    protocol: TCP
    targetPort: 1516
  selector:
    app: wazuh-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
