apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"metallb.io/loadBalancerIPs":"10.10.0.162","metallb.universe.tf/loadBalancerIPs":"10.10.0.162"},"labels":{"app.kubernetes.io/component":"wazuh-manager","app.kubernetes.io/part-of":"iiot-correlation-lab","iiot-lab/scenario":"C"},"name":"wazuh-manager-lb","namespace":"security"},"spec":{"ports":[{"name":"agent-events","port":1514,"protocol":"TCP","targetPort":1514},{"name":"agent-registration","port":1515,"protocol":"TCP","targetPort":1515},{"name":"wazuh-api","port":55000,"protocol":"TCP","targetPort":55000}],"selector":{"app":"wazuh-manager","node-type":"master"},"type":"LoadBalancer"}}
    metallb.io/loadBalancerIPs: 10.10.0.162
    metallb.universe.tf/loadBalancerIPs: 10.10.0.162
  creationTimestamp: "2026-05-02T04:43:01Z"
  labels:
    app.kubernetes.io/component: wazuh-manager
    app.kubernetes.io/part-of: iiot-correlation-lab
    iiot-lab/scenario: C
  name: wazuh-manager-lb
  namespace: security
  resourceVersion: "53710"
  uid: d816f1f9-02fb-4029-b409-d03599021b5f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.152.183.45
  clusterIPs:
  - 10.152.183.45
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.10.0.162
  ports:
  - name: agent-events
    nodePort: 31936
    port: 1514
    protocol: TCP
    targetPort: 1514
  - name: agent-registration
    nodePort: 31645
    port: 1515
    protocol: TCP
    targetPort: 1515
  - name: wazuh-api
    nodePort: 31472
    port: 55000
    protocol: TCP
    targetPort: 55000
  selector:
    app: wazuh-manager
    node-type: master
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.10.0.162
      ipMode: VIP
