#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

KUBECTL="${KUBECTL:-microk8s kubectl}"
TZ_NAME="${TZ_NAME:-America/Lima}"
OUT_DIR="${OUT_DIR:-results/tables}"
EVIDENCE_DIR="${EVIDENCE_DIR:-evidence/readiness}"
OUT_CSV="$OUT_DIR/table_scenario_readiness.csv"
OUT_JSON="$EVIDENCE_DIR/scenario_readiness_summary.json"
OUT_MD="$EVIDENCE_DIR/scenario_readiness_summary.md"

mkdir -p "$OUT_DIR" "$EVIDENCE_DIR"

now_local() { TZ="$TZ_NAME" date '+%Y-%m-%d %H:%M:%S %z (%Z)'; }
now_utc() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
line() { printf '%s\n' '============================================================'; }
phase() {
  printf '\n------------------------------------------------------------\n'
  printf '[PHASE %s] ES: %s\n' "$1" "$2"
  printf '[PHASE %s] EN: %s\n' "$1" "$3"
  printf '%s\n\n' '------------------------------------------------------------'
}
ok() { printf '[OK] ES: %s\n[OK] EN: %s\n' "$1" "$2"; }
warn() { printf '[WARN] ES: %s\n[WARN] EN: %s\n' "$1" "$2"; }

line
echo "[SCRIPT START] 28-validate-scenario-readiness.sh"
echo "Hora de inicio / Start time: $(now_local)"
echo "ES: Validar preparación y evidencia de escenarios A–E."
echo "EN: Validate readiness and evidence for scenarios A–E."
line

phase "1/6" "Inicializar tabla de readiness." "Initialize readiness table."

cat > "$OUT_CSV" <<'EOF'
scenario,role,status,required_evidence,observed_evidence,notes
EOF

add_row() {
  local scenario="$1" role="$2" status="$3" required="$4" observed="$5" notes="$6"
  printf '"%s","%s","%s","%s","%s","%s"\n' \
    "$scenario" "$role" "$status" "$required" "$observed" "$notes" >> "$OUT_CSV"
}

status_ok="OK"
status_warn="WARN"

phase "2/6" "Validar Escenario A — Foundation IIoT." "Validate Scenario A — Foundation IIoT."

a_status="$status_ok"
a_obs=()

if $KUBECTL get ns iiot-poc >/dev/null 2>&1; then a_obs+=("namespace iiot-poc"); else a_status="$status_warn"; a_obs+=("missing namespace iiot-poc"); fi
if $KUBECTL get pods -n iiot-poc --no-headers 2>/dev/null | grep -q "Running"; then a_obs+=("running pods"); else a_status="$status_warn"; a_obs+=("no running pods"); fi
if $KUBECTL get svc -n iiot-poc >/dev/null 2>&1; then a_obs+=("services exported"); else a_status="$status_warn"; a_obs+=("missing services"); fi

for url in \
  "http://10.10.0.152:8080/health" \
  "http://10.10.0.153:8080/health" \
  "http://10.10.0.154:8080/health"
do
  code="$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "$url" || true)"
  if [[ "$code" == "200" ]]; then
    a_obs+=("$url=200")
  else
    a_status="$status_warn"
    a_obs+=("$url=$code")
  fi
done

add_row "A" "Functional foundation" "$a_status" \
  "namespace, pods, services, healthy IIoT endpoints" \
  "$(IFS='; '; echo "${a_obs[*]}")" \
  "A is a construction/functional validation scenario, not a statistical campaign."

phase "3/6" "Validar Escenario B — Zabbix Monitoring." "Validate Scenario B — Zabbix Monitoring."

b_status="$status_ok"
b_obs=()

if $KUBECTL get ns monitoring >/dev/null 2>&1; then b_obs+=("namespace monitoring"); else b_status="$status_warn"; b_obs+=("missing namespace monitoring"); fi
if $KUBECTL get pods -n monitoring --no-headers 2>/dev/null | grep -q "zabbix"; then b_obs+=("zabbix pods present"); else b_status="$status_warn"; b_obs+=("zabbix pods missing"); fi

if [[ -f results/raw/scenario_d/zabbix_history_validation.csv ]]; then
  rows="$(python3 - <<'PY'
from pathlib import Path
p=Path("results/raw/scenario_d/zabbix_history_validation.csv")
print(max(sum(1 for _ in p.open(encoding="utf-8"))-1,0))
PY
)"
  b_obs+=("zabbix history validation rows=$rows")
else
  b_status="$status_warn"
  b_obs+=("missing zabbix_history_validation.csv")
fi

if [[ -f results/tables/table_zabbix_history_quality.csv ]]; then
  b_obs+=("history quality table")
else
  b_status="$status_warn"
  b_obs+=("missing history quality table")
fi

# Project-specific Zabbix export detection.
# Accepts the canonical export generated by script 10 as well as the later real-monitoring export set.
zbx_exports=()
while IFS= read -r f; do zbx_exports+=("$f"); done < <(
  find evidence/zabbix baseline -type f \( \
    -name "zabbix_configuration_summary.md" -o \
    -name "zabbix_hostgroups.json" -o \
    -name "zabbix_hosts.json" -o \
    -name "zabbix_items.json" -o \
    -name "zabbix_triggers.json" -o \
    -name "zabbix-zabbix-hosts-real-monitoring.json" -o \
    -name "zabbix-zabbix-items-real-monitoring.json" -o \
    -name "zabbix-zabbix-triggers-real-monitoring.json" -o \
    -name "zabbix-zabbix-real-monitoring-summary.csv" \
  \) 2>/dev/null | sort
)

if [[ "${#zbx_exports[@]}" -gt 0 ]]; then
  b_obs+=("zabbix config/runtime exports found=${#zbx_exports[@]}")
  printf '%s\n' "${zbx_exports[@]}" > "$EVIDENCE_DIR/zabbix_export_files_detected.txt"
else
  b_status="$status_warn"
  b_obs+=("missing zabbix config/runtime exports")
fi

# Scenario B freeze validation.
if [[ -d baseline/scenario_B_20260502_033417 || -f baseline/scenario_B_20260502_033417.tar.gz ]]; then
  b_obs+=("scenario B freeze present")
else
  b_status="$status_warn"
  b_obs+=("scenario B freeze not found")
fi

add_row "B" "Operational instrumentation" "$b_status" \
  "Zabbix namespace/pods, hosts/items/triggers export, history evidence, history quality table, scenario B freeze" \
  "$(IFS='; '; echo "${b_obs[*]}")" \
  "B validates monitoring instrumentation; quantitative attack analysis is performed in D."

phase "4/6" "Validar Escenario C — Wazuh Security." "Validate Scenario C — Wazuh Security."

c_status="$status_ok"
c_obs=()

if $KUBECTL get ns security >/dev/null 2>&1; then c_obs+=("namespace security"); else c_status="$status_warn"; c_obs+=("missing namespace security"); fi
if $KUBECTL get pods -n security --no-headers 2>/dev/null | grep -q "wazuh"; then c_obs+=("wazuh pods present"); else c_status="$status_warn"; c_obs+=("wazuh pods missing"); fi
if $KUBECTL get svc -n security 2>/dev/null | grep -q "wazuh-dashboard"; then c_obs+=("wazuh dashboard service"); else c_status="$status_warn"; c_obs+=("missing dashboard service"); fi
if $KUBECTL get svc -n security 2>/dev/null | grep -q "55000"; then c_obs+=("wazuh api service"); else c_obs+=("wazuh api service not explicitly detected"); fi
if [[ -f results/raw/scenario_c/wazuh_security_baseline.csv || -f baseline/scenario_c_wazuh_security/wazuh_security_baseline.csv ]]; then c_obs+=("scenario C baseline dataset"); else c_status="$status_warn"; c_obs+=("missing scenario C baseline dataset"); fi
if [[ -d evidence/wazuh ]]; then c_obs+=("wazuh evidence directory"); else c_status="$status_warn"; c_obs+=("missing wazuh evidence directory"); fi
if [[ -d baseline/scenario_c_wazuh_security || -f baseline/scenario_c_wazuh_security.tar.gz ]]; then c_obs+=("scenario C freeze present"); else c_status="$status_warn"; c_obs+=("scenario C freeze not found"); fi

add_row "C" "Security instrumentation" "$c_status" \
  "Wazuh namespace/pods/services, dashboard/API, baseline/evidence, scenario C freeze" \
  "$(IFS='; '; echo "${c_obs[*]}")" \
  "C validates security instrumentation; attack campaign evidence is produced in D."

phase "5/6" "Validar Escenarios D y E — campañas cuantitativas." "Validate Scenarios D and E — quantitative campaigns."

d_status="$status_ok"
d_obs=()

if [[ -f results/processed/correlation_dataset.csv ]]; then
  d_rows="$(python3 - <<'PY'
from pathlib import Path
p=Path("results/processed/correlation_dataset.csv")
print(max(sum(1 for _ in p.open(encoding="utf-8"))-1,0))
PY
)"
  d_obs+=("correlation rows=$d_rows")
  [[ "$d_rows" -eq 60 ]] || d_status="$status_warn"
else
  d_status="$status_warn"; d_obs+=("missing correlation_dataset.csv")
fi

for f in \
  results/tables/table_attack_detection.csv \
  results/tables/table_temporal_correlation_summary.csv \
  results/tables/table_bootstrap_ci.csv \
  results/tables/table_mttd_estimation.csv
do
  if [[ -f "$f" ]]; then d_obs+=("$(basename "$f")"); else d_status="$status_warn"; d_obs+=("missing $(basename "$f")"); fi
done

if [[ -d baseline/scenario_d_correlation_20260502T200142Z || -f baseline/scenario_d_correlation_20260502T200142Z.tar.gz ]]; then
  d_obs+=("paper-final scenario D freeze present")
else
  d_status="$status_warn"
  d_obs+=("paper-final scenario D freeze not found")
fi

add_row "D" "Quantitative attack/correlation campaign" "$d_status" \
  "60 attack executions, correlation dataset, temporal deltas, statistical tables, scenario D freeze" \
  "$(IFS='; '; echo "${d_obs[*]}")" \
  "D is the main attack detection and event-based temporal correlation campaign."

e_status="$status_ok"
e_obs=()

if [[ -f results/raw/scenario_e/noise_events.csv ]]; then
  e_rows="$(python3 - <<'PY'
from pathlib import Path
p=Path("results/raw/scenario_e/noise_events.csv")
print(max(sum(1 for _ in p.open(encoding="utf-8"))-1,0))
PY
)"
  e_obs+=("noise rows=$e_rows")
  [[ "$e_rows" -eq 60 ]] || e_status="$status_warn"
else
  e_status="$status_warn"; e_obs+=("missing noise_events.csv")
fi

if [[ -f results/raw/scenario_e/http_endpoint_validation_summary.json ]]; then
  http_errors="$(python3 - <<'PY'
import json
from pathlib import Path
data=json.loads(Path("results/raw/scenario_e/http_endpoint_validation_summary.json").read_text(encoding="utf-8"))
print(data.get("http_error_count","MISSING"))
PY
)"
  e_obs+=("http_errors=$http_errors")
  [[ "$http_errors" == "0" ]] || e_status="$status_warn"
else
  e_status="$status_warn"; e_obs+=("missing http_endpoint_validation_summary.json")
fi

for f in \
  results/tables/table_noise_fpr_summary.csv \
  results/tables/table_noise_wilson_ci.csv \
  results/tables/table_noise_profile_summary.csv
do
  if [[ -f "$f" ]]; then e_obs+=("$(basename "$f")"); else e_status="$status_warn"; e_obs+=("missing $(basename "$f")"); fi
done

if [[ -d baseline/scenario_e_noise_fpr_20260503T033658Z || -f baseline/scenario_e_noise_fpr_20260503T033658Z.tar.gz ]]; then
  e_obs+=("paper-final scenario E freeze present")
else
  e_status="$status_warn"
  e_obs+=("paper-final scenario E freeze not found")
fi

add_row "E" "Quantitative operational-noise/FPR control campaign" "$e_status" \
  "60 legitimate noise executions, 0 HTTP errors, FPR table, Wilson CI, scenario E freeze" \
  "$(IFS='; '; echo "${e_obs[*]}")" \
  "E is the false-positive control campaign under legitimate operational variability."

phase "6/6" "Generar resumen JSON y Markdown." "Generate JSON and Markdown summary."

python3 - <<'PY'
import csv, json
from pathlib import Path
from datetime import datetime, timezone

csv_path=Path("results/tables/table_scenario_readiness.csv")
json_path=Path("evidence/readiness/scenario_readiness_summary.json")
md_path=Path("evidence/readiness/scenario_readiness_summary.md")
zbx_list=Path("evidence/readiness/zabbix_export_files_detected.txt")

rows=list(csv.DictReader(csv_path.open(encoding="utf-8")))
summary={
    "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "overall_status": "OK" if all(r["status"]=="OK" for r in rows) else "WARN",
    "scenarios": rows,
    "zabbix_export_files_detected": zbx_list.read_text(encoding="utf-8").splitlines() if zbx_list.exists() else [],
    "methodological_positioning": {
        "A": "functional foundation",
        "B": "operational instrumentation",
        "C": "security instrumentation",
        "D": "quantitative attack/correlation campaign",
        "E": "quantitative operational-noise/FPR control campaign"
    }
}
json_path.write_text(json.dumps(summary,indent=2,ensure_ascii=False),encoding="utf-8")

md=["# Scenario readiness summary", "", f"- Generated UTC: `{summary['generated_utc']}`", f"- Overall status: `{summary['overall_status']}`", ""]
md.append("| Scenario | Role | Status | Notes |")
md.append("|---|---|---|---|")
for r in rows:
    md.append(f"| {r['scenario']} | {r['role']} | {r['status']} | {r['notes']} |")
md.append("")
md.append("## Zabbix export evidence")
md.append("")
if summary["zabbix_export_files_detected"]:
    for f in summary["zabbix_export_files_detected"]:
        md.append(f"- `{f}`")
else:
    md.append("- No Zabbix export files detected.")
md.append("")
md.append("## Methodological interpretation")
md.append("")
md.append("A–C are construction/instrumentation validation scenarios. D and E are the quantitative campaigns used for statistical analysis.")
md_path.write_text("\n".join(md)+"\n",encoding="utf-8")

print(json.dumps(summary,indent=2,ensure_ascii=False))
PY

line
echo "[SUMMARY] Scenario Readiness Validation v2"
line
ok "Tabla generada: $OUT_CSV" "Generated table: $OUT_CSV"
ok "Resumen JSON generado: $OUT_JSON" "Generated JSON summary: $OUT_JSON"
ok "Resumen Markdown generado: $OUT_MD" "Generated Markdown summary: $OUT_MD"
ok "Lista de exports Zabbix: $EVIDENCE_DIR/zabbix_export_files_detected.txt" "Zabbix export list: $EVIDENCE_DIR/zabbix_export_files_detected.txt"

if grep -q ',"WARN",' "$OUT_CSV"; then
  warn "Existen advertencias de readiness. Revisar $OUT_CSV." "Readiness warnings exist. Review $OUT_CSV."
else
  ok "Todos los escenarios A–E están listos según el rol metodológico definido." "All scenarios A–E are ready according to the defined methodological role."
fi

line
echo "[EXECUTION END]"
echo "Script: 28-validate-scenario-readiness.sh"
echo "Hora de fin / End time: $(now_local)"
echo "Exit code: 0"
line
