apiVersion: v1
data:
  key: MTIzYTQ1YmM2N2RlZjg5MWdoMjNpNDVqazY3bDhtbjk=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"key":"MTIzYTQ1YmM2N2RlZjg5MWdoMjNpNDVqazY3bDhtbjk="},"kind":"Secret","metadata":{"annotations":{},"name":"wazuh-cluster-key","namespace":"security"}}
  creationTimestamp: "2026-05-02T04:43:05Z"
  name: wazuh-cluster-key
  namespace: security
  resourceVersion: "53484"
  uid: 17bd4e15-9eb9-418d-8fa7-cb9c4a199271
type: Opaque
